config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  get 'about', to: 'static#about'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'


  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password validations: true
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA256.hexdigest(token.to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :current_user
  # before_action :require_sign_in!
  helper_method :signed_in?

  protect_from_forgery with: :exception

  def current_user
    remember_token = User.encrypt(cookies[:user_remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end


  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:user_remember_token] = remember_token
    user.update!(remember_token: User.encrypt(remember_token))
    @current_user = user
  end

  def sign_out
    cookies.delete(:user_remember_token)
  end

  def signed_in?
    @current_user.present?
  end

  private

    def require_sign_in!
      redirect_to login_path unless signed_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_sign_in!, only: [:destroy]
  before_action :set_user, only: [:create]
  skip_before_action :require_sign_in!, only: [:new, :create]

  def new
  end

  def create
    if @user.authenticate(session_params[:password])
      sign_in(@user)
      redirect_to root_path
    else
      flash.now[:danger] = t('.flash.invalide_password')
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

     def set_user
       @user = User.find_by!(email: session_params[:email])
     rescue
       flash.now[:danger] = t('.flash.invalid_email')
       render action: 'new'
     end

     def session_params
       params.require(:session).permit(:email, :password)
     end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to login_path
    else
      render action: :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teachers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit画面</h1>

<div class="">
  <%= form_for @user do |f| %>

     <p>
       <%= f.label :name, 'ユーザー名' %>
       <%= f.text_field :name %>
     </p>

     <p>
       <%= f.label :email, "メールアドレス" %>
       <%= f.text_field :email %>
     </p>

     <%= f.submit('更新') %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>TEACHERS</h1>
<div class="sign_menu">
  <% if signed_in? %>
    <li><%= link_to "マイページ", "/users/#{@current_user.id}" %></li>
    <li><%= link_to "ログアウト", logout_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to "新規登録", new_user_path %></li>
    <li><%= link_to "ログイン", login_path %></li>
  <% end %>
</div>
<div class="menu">
  <ul>
    <li><%= link_to "ホーム", root_path %></li>
    <li><%= link_to "TEACHERSとは", about_path %></li>
  </ul>
</div>

<div class="user-list">
  <h2>ユーザー一覧</h2>
  <% @users.each do |user| %>
    <%= user.name %><br>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>新規登録画面</h1>

<%= form_for @user do |f| %>
   <% if @user.errors.any? %>
     <h3>入力した内容にエラーが<%= @user.errors.count %>件あります</h3>
     <ul>
       <% @user.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
     </ul>
   <% end %>

   <p>
     <%= f.label :name, 'ユーザー名' %>
     <%= f.text_field :name %>
   </p>

   <p>
     <%= f.label :email, "メールアドレス" %>
     <%= f.text_field :email %>
   </p>

   <p>
     <%= f.label :password, "パスワード"%>
     <%= f.password_field :password %>
   </p>

   <p>
     <%= f.label :password_confirmation, "パスワード確認" %>
     <%= f.password_field :password_confirmation %>
   </p>

   <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>プロフィール</h1>
<table>
  <tr>
    <th>名前</th>
    <td><%= @user.name %></td>
  </tr>
  <tr>
    <th>メールアドレス</th>
    <td><%= @user.email %></td>
  </tr>
</table>